### ISSUE TITLE
Ambiguous message when no "ca" key is present in secret

### ISSUE THREAD

**Issue by carlosgonzalezp** [jet/kube-webhook-certgen#13]
https://github.com/jet/kube-webhook-certgen/blob/c80b04ec466f1e752e837763089caf937f61e148/pkg/k8s/k8s.go#L109

The error message when no "ca" key is present in a secret is "got secret, but it did not contain a 'cert' key", but it should be "... not contain a 'ca' key". This is ambiguous and confusing :)

Thanks.

**Comment by vsliouniaev** [comment]
Thanks for the report!
