### ISSUE TITLE
Add s390x support for kube-webhook-certgen docker image 

### ISSUE THREAD

**Issue by sid226** [jet/kube-webhook-certgen#15]
Error while pulling image on s390x machine.

``` 
Failed to pull image "jettech/kube-webhook-certgen:v1.2.0": rpc error: code = Unknown desc = no matching manifest for linux/s390x in the manifest list entries
```

**Comment by vsliouniaev** [comment]
@sid226 Could you check if v1.2.2 works for you?

**Comment by sid226** [comment]
@vsliouniaev  Yes its working. Thanks. 
is it possible to add for 1.2.1 as well?

**Comment by vsliouniaev** [comment]
I don't want to alter the existing docker manifest for anyone who may be already using it.

There are no code changes between 1.2.1 and 1.2.2, just an amended CI process to build an image for the target architecture.
