### ISSUE TITLE
openssl vulnerabilities

### ISSUE THREAD

**Issue by HenriAW** [jet/kube-webhook-certgen#27]
My security scanner has flagged the following vulnerabilities related to openssl

[DLA-2563-1](https://www.debian.org/lts/security/2021/dla-2563)
[DLA-2492-1](https://security-tracker.debian.org/tracker/DLA-2492-1)

**Comment by vsliouniaev** [comment]
Should be fixed in 1.5.2 by switching to a base image without openssl. Please confirm.
