### ISSUE TITLE
Generate secret of type kubernetes.io/tls with standard keys

### ISSUE THREAD

**Issue by invidian** [jet/kube-webhook-certgen#29]
As the code generates a TLS certificate, I think it would be reasonable to generate a secret of standarized type `kubernetes.io/tls` and use standard keys of `tls.key` and `tls.crt` associated with it. This is the same what e.g. cert-manager generates, so it allows easy interoperability.

Right now as a workaround, one can use `--cert-name=tls.crt` and `--key-name=tls.key` flags.

**Comment by vsliouniaev** [comment]
Thanks for your suggestion, will consider including it in the next release.
