### ISSUE TITLE
Update to k8s.io/api/admissionregistration/v1

### ISSUE THREAD

**Issue by invidian** [jet/kube-webhook-certgen#30]
`k8s.io/api/admissionregistration/v1beta1` is deprecated since Kubernetes 1.16+ and will be removed in 1.22+. Code should be updated to use new API types.

**Comment by jonkerj** [comment]
This bug causes kube-webhook-certgen to bail/fail on Kubernetes 1.22:

```
jorik@argon:$ kubectl logs -n monitoring kps-admission-patch--1-mtzsk
W0826 10:16:43.550360       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"level":"info","msg":"patching webhook configurations 'kps-admission' mutating=true, validating=true, failurePolicy=Fail","source":"k8s/k8s.go:39","time":"2021-08-26T10:16:43Z"}
{"err":"the server could not find the requested resource","level":"fatal","msg":"failed getting validating webhook","source":"k8s/k8s.go:48","time":"2021-08-26T10:16:43Z"}
```

**Comment by brandond** [comment]
For anyone finding this issue, as per @vsliouniaev 

> I no longer have access rights to this repository and it is no longer being maintained by the company. There is already a fork of this in the [ingress-nginx repo](https://github.com/kubernetes/ingress-nginx/tree/main/images/kube-webhook-certgen), which has updated APIs and is hosted on GCR: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L569

**Comment by alyiox** [comment]
please try to use `k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1` instead.

**Comment by invidian** [comment]
I'll close this issue as `k8s.gcr.io/ingress-nginx/kube-webhook-certgen` is now likely considered upstream.

**Comment by stigok** [comment]
> I'll lose this issue as `k8s.gcr.io/ingress-nginx/kube-webhook-certgen` is now likely considered upstream.

I think this issue should be left open for exactly this reason.
