### ISSUE TITLE
Multiarch Docker images

### ISSUE THREAD

**Issue by mcanevet** [jet/kube-webhook-certgen#9]
Would it be possible to provide multi-arch (especially amd64 and arm64 in my case) images on DockerHub. This images is used in prometheus-operator and I try to deploy it on a mixed arch cluster.

**Comment by vsliouniaev** [comment]
This is a good idea, but will probably take me some time to get to.

**Comment by vsliouniaev** [comment]
@mcanevet, looks like this isn't that complex as I expected. Could you please check if `jettech/kube-webhook-certgen:v1.1.0` works for you?

**Comment by mcanevet** [comment]
Looks like it works fine. Thanks a lot.

**Comment by vsliouniaev** [comment]
Good to know, I'll close the issue
